### ISSUE TITLE
ReflectionException not found class yii\twocheckout\Twocheckout

### ISSUE THREAD

**Issue by kirc0de** [joni-jones/yii2-2checkout#1]
I developed my website on windows server and it's ok.

But on linux server I get this error:

`Class yii\twocheckout\Twocheckout does not exist`

There are 2 ways to resolve the problem:
1. rename TwoCheckout.php into Twocheckout.php (bad way)
2. change your config: `'class' => 'yii\twocheckout\Twocheckout'` => `'class' => 'yii\twocheckout\TwoCheckout'` (good way)

**Comment by YevSent** [comment]
Thanks for your feedback, this is typo in readme.md should be `'class' => 'yii\twocheckout\TwoCheckout'` in the configuration.
Fixed.
